# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:488.0.0@sha256:809983a1f057a8dd874e160ef2d4edb10f0f141b0664104435891d1520e0e4ad
RUN apt-get install -y netcat
